### ISSUE TITLE
Bug: CSS da Agenda Não Está Carregando

### ISSUE THREAD

**Issue by AdrianMichael5** [rafaelserpaa/advocatus#36]
#### Resumo
O CSS da seção de agenda não está sendo carregado corretamente. Apenas o estilo da navbar está sendo aplicado, resultando em uma apresentação inadequada da seção de agenda.

#### Descrição do Problema
Atualmente, ao acessar a página da agenda, os estilos específicos para essa seção não estão sendo aplicados. Enquanto a navbar carrega normalmente, o restante da página de agenda aparece sem formatação adequada.

#### Comportamento Esperado
A seção da agenda deve ser exibida com todos os estilos aplicados, garantindo que o layout e a estética sejam mantidos.

#### Comportamento Observado
A navbar está estilizada corretamente, mas a seção da agenda aparece sem formatação, como se o CSS correspondente não estivesse sendo carregado.

#### Passos para Reproduzir
1. Acesse a URL da seção de agenda.
2. Observe que apenas os estilos da navbar estão sendo aplicados, enquanto o restante da página apresenta formatação padrão.

#### Impacto
Esse problema prejudica a experiência do usuário e a apresentação da seção de agenda, o que pode levar a uma percepção negativa do site.

#### Ambiente
- **Sistema Operacional**: Windows 10
- **Navegador**: Chrome 94.0

#### Prioridade
Média

**Comment by BrunofCarvalhoo** [comment]
A issue foi resolvida com o commit [9637445b4b872621564652d284c7eca10c04a20e](https://github.com/rafaelserpaa/advocatus/commit/9637445b4b872621564652d284c7eca10c04a20e). O problema com o carregamento do CSS da seção de agenda foi corrigido. Agora, a seção está sendo exibida corretamente, com todos os estilos aplicados.

Agradeço a todos que contribuíram para identificar e discutir essa questão. Se alguém encontrar mais problemas relacionados ao CSS ou à apresentação da agenda, sinta-se à vontade para abrir uma nova issue.
